### ISSUE TITLE
Migration Issue - The operation could not be completed. (PostgresNIO.PSQLError error 1.)

### ISSUE THREAD

**Issue by mdellagi77** [hummingbird-project/hummingbird-fluent#32]
First of all I love Hummingbird 2 and Fluent. 
Thank you very much for your effort!

I am building a small backend for an app and everything is great and works seemlessly.

But now I am running into an issue. I just added a new field `surname`

```
@Field(key: "surname")
var surname: String
```

And execute the following migration

```
struct AddSurnameEventMigration: AsyncMigration {
    func prepare(on database: Database) async throws {
        try await database.schema("events")
            .field("surname", .string) // Add the surname field
            .update()
    }

    func revert(on database: Database) async throws {
        try await database.schema("events")
            .deleteField("surname") // Remove the surname field
            .update()
    }
}
```

After making a Post request with the Controller responds with 200 and returns the whole model including the new `surname`
![Screenshot 2024-11-22 at 21 25 00](https://github.com/user-attachments/assets/a6cc7ac0-eb4d-43a5-b66d-3ce8c6166926)

But it is not stored to the DB as I am seeing the error

```
binds=["64FCCE08-8591-4850-A481-E39F6C94A036", "Alpine", "Schulz", "2023-10-01 12:00:00 +0000", "ferrata", "18", "50.105849", "14.413999"] database-id=psql sql=INSERT INTO "events" ("id", "name", "surname", "date", "kind", "spots_left", "coordinates_latitude", "coordinates_longitude") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id" [PostgresKit] Executing query
The operation could not be completed. (PostgresNIO.PSQLError error 1.)
```
Also the DB schema was not updated with a new surname field

Help please. What am I doing wrong?

**Comment by adam-fowler** [comment]
I know this may sound like an odd question but is your migration really called `CreateEventMigration`? What was the migration that actually created the "events" table called?

**Comment by mdellagi77** [comment]
Nicely spotted. No it is actually called AddSurnameEventMigration

**Comment by mdellagi77** [comment]
Now the schema is updated. But the same error is still appearing when doing the POST

**Comment by mdellagi77** [comment]
Please close the issue. I dropped the DB and started over the migration. Now everything is working as expected

**Comment by adam-fowler** [comment]
@mdellagi77 in the future for fluent specific issues you are probably better adding issues to [fluent-kit ](https://github.com/vapor/fluent-kit). There are people there with more experience of fluent there.
